version: '{build}'
clone_folder: c:\gopath\src\git.cm\naiba\gocd
init:
- cmd: git config --global core.autocrlf input
environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.9
install:
- cmd: >-
    cd c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

    dir

    rmdir c:\go /s /q

    appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi

    msiexec /i go%GOVERSION%.windows-amd64.msi /q

    set Path=c:\go\bin;c:\gopath\bin;c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

    go version

    go env
build: off
test_script:
- cmd: >-
    go build git.cm/naiba/gocd/cmd/web

    for /f "" %%G in ('go list git.cm/naiba/gocd/...') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)
deploy: off