version: '{build}'
clone_folder: c:\go\src\git.cm\naiba\gocd
init:
- cmd: git config --global core.autocrlf input
environment:
  GOPATH: c:\go
  DEPTESTBYPASS501: 1
  CC: c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\gcc.exe
install:
- cmd: >-
    set Path=c:\go\bin;c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

    go version

    go env
build: off
test_script:
- cmd: >-
    go build git.cm/naiba/gocd/cmd/web

    for /f "" %%G in ('go list git.cm/naiba/gocd/...') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)
deploy: off